### ISSUE TITLE
Add Page-Level Tags

### ISSUE THREAD

**Issue by VarunS1997** [Project-Hedron/Issues-and-Tasks#18]
The Search Sections tags have been fairly good so far. We should expand the functionalities to allow pages themselves to have aliases.

**Comment by HLMelton** [comment]
Frontend Branch : https://github.com/Tabletop-Mirror/tabletop-mirror-front-end/tree/2024.06.02/HLMelton-PageTags

Models Branch: https://github.com/Tabletop-Mirror/Tabletop-Mirror-Models/tree/2024.06.05/HLMelton-Page-Tags

**Comment by HLMelton** [comment]
It wasn't allowing me to create the specific version branch (Ex: 2024.06.02) so I attached links to the specific branches for their respective repos above regarding this issue. 

Should we move these changes over to a different branch with a different name since Git isn't allowing me to create a branch with the proper naming schema? I attached the error provided below:
```
git checkout -b 2024.06.02

fatal: cannot lock ref 'refs/heads/2024.06.02': 'refs/heads/2024.06.02/HLMelton-PageTags' exists; cannot create 'refs/heads/2024.06.02'
```

**Comment by VarunS1997** [comment]
Verified the functionality and added to 2024.06.02. Slated for deployment.
